version: '3'
services:
  api:
    image: triplee1/crudapi
    depends_on:
      - postgres
    ports:
      - 80:8000
    command: uvicorn apps.main:app --host 0.0.0.0 --port 80
    env_file:
      - ./.env
  postgres:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgres/data

volumes:
  postgres-db:
