version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:./:ro
    command: uvicorn apps.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./.env
  postgres:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgres/data

volumes:
  postgres-db:
