name: Build and Deploy
on:
  push:
    branches:
      - "main"
      - "test"
      - "production"
      - "development"
  pull_request:
    branches:
      - "development"
      - "test"
      - "production"
      - "main"
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling from git repo
        uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Update PIP
        run: python3 -m pip install --upgrade pip
      - name: Install Project Dependencies
        run: pip install -r requirements.txt