name: Build and Deploy
on:
  push:
    branches:
      - "main"
      - "test"
      - "production"
      - "development"
  pull_request:
    branches:
      - "development"
      - "test"
      - "production"
      - "main"
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling from git repo
        uses: actions/checkout@v2
      - name: Deploying from git repo
        run: echo "Deploying from git repo"