name: Build and Deploy
on:
  push:
    branches:
      - "main"
      - "test"
      - "production"
      - "development"
  pull_request:
    branches:
      - "development"
      - "test"
      - "production"
      - "main"
jobs:
  job_1:
    environment:
      name: testing
    env:
      OAUTH2_SECRET_KEY: ${{secrets.OAUTH2_SECRET_KEY}}
      DB_USER_PASSW: ${{secrets.DB_USER_PASSW}}
      DB_NAME: ${{secrets.DB_NAME}}
      ACCESS_TOKEN_EXPIRE_WEEKS: ${{secrets.ACCESS_TOKEN_EXPIRE_WEEKS}}
      ALGORITHM: ${{secrets.ALGORITHM}}
    runs-on: ubuntu-latest
    steps:
      - name: Pulling from git repo
        uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Update PIP
        run: python3 -m pip install --upgrade pip
      - name: Install Project Dependencies
        run: pip install -r requirements.txt
      - name: Install Pytest and Run Tests
        run: |
          pip install pytest
          pytest -v -s